<?php
return array(
	'login'=>array(
		'title'=>'ログイン',
		'keyword'=>'ログイン',
		'description'=>'ログイン',
		'h1_tag'=>'ログイン',
	),
	'mailsend'=>array(
		'title'=>'会員登録',
		'keyword'=>'会員登録',
		'description'=>'会員登録',
		'h1_tag'=>'会員登録',
	),
	'mailinput'=>array(
		'title'=>'会員登録',
		'keyword'=>'会員登録',
		'description'=>'会員登録',
		'h1_tag'=>'会員登録',
	),
	'remind'=>array(
		'title'=>'パスワード再発行',
		'keyword'=>'パスワード再発行',
		'description'=>'パスワード再発行',
		'h1_tag'=>'パスワード再発行',
	),
);